# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id_asiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('grid_row', models.IntegerField()),
                ('grid_col', models.IntegerField()),
                ('numero_asiento', models.IntegerField()),
                ('existe', models.IntegerField()),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.DO_NOTHING, to='zonas.zonas')),
            ],
            options={
                'db_table': 'asientos',
                'ordering': ['id_asiento'],
            },
        ),
    ]
