# Generated by Django 6.0.3 on 2026-04-10 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0001_initial'),
        ('eventos', '0008_alter_eventos_estatus'),
        ('grid_cells', '0001_initial'),
        ('usuarios', '0003_alter_usuarios_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='id_grid_cell',
            field=models.ForeignKey(blank=True, db_column='id_grid_cell', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid_cells.gridcells'),
        ),
        migrations.CreateModel(
            name='EstadoAsientoEvento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('retenido', 'Retenido'), ('vendido', 'Vendido')], default='disponible', max_length=12)),
                ('retenido_hasta', models.DateTimeField(blank=True, null=True)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos')),
                ('id_grid_cell', models.ForeignKey(db_column='id_grid_cell', on_delete=django.db.models.deletion.CASCADE, to='grid_cells.gridcells')),
                ('retenido_por', models.ForeignKey(blank=True, db_column='retenido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'estado_asiento_evento',
                'ordering': ['id'],
                'unique_together': {('id_grid_cell', 'id_evento')},
            },
        ),
    ]
