# Generated by Django 6.0.1 on 2026-04-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuarios_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLogs',
            fields=[
                ('id_auditoria_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, default='', max_length=45)),
                ('accion', models.CharField(max_length=60)),
                ('valores_antes', models.JSONField(blank=True, null=True)),
                ('valores_despues', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'auditoria_logs',
                'ordering': ['id_auditoria_log'],
            },
        ),
    ]
