# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLogs',
            fields=[
                ('id_auditoria_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=60)),
                ('entidad', models.CharField(blank=True, max_length=45, null=True)),
                ('id_entidad', models.IntegerField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'auditoria_logs',
                'ordering': ['id_auditoria_log'],
            },
        ),
    ]
