# Generated by Django 6.0.1 on 2026-04-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialogs',
            name='entidad',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
