# Generated by Django 6.0.3 on 2026-04-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_logs', '0002_alter_auditorialogs_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialogs',
            name='entidad',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
