# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_orden', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('estatus', models.CharField(max_length=9)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.eventos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'ordenes',
                'ordering': ['id_orden'],
            },
        ),
    ]
