# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioZonaEvento',
            fields=[
                ('id_precio_zona_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha_creación', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.eventos')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.DO_NOTHING, to='zonas.zonas')),
            ],
            options={
                'db_table': 'precio_zona_evento',
                'ordering': ['id_precio_zona_evento'],
            },
        ),
    ]
