# Generated by Django 6.0.1 on 2026-04-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precio_zona_evento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciozonaevento',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
    ]
