# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layouts', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridCells',
            fields=[
                ('id_grid_cells', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=16)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('id_layout', models.ForeignKey(db_column='id_layout', on_delete=django.db.models.deletion.DO_NOTHING, to='layouts.layouts')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.DO_NOTHING, to='zonas.zonas')),
            ],
            options={
                'db_table': 'grid_cells',
                'ordering': ['id_grid_cells'],
            },
        ),
    ]
