# Generated by Django 6.0.3 on 2026-04-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_cells', '0001_initial'),
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridcells',
            name='id_zona',
            field=models.ForeignKey(blank=True, db_column='id_zona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zonas.zonas'),
        ),
    ]
