# Generated by Django 6.0.1 on 2026-04-14 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_cells', '0002_alter_gridcells_id_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcells',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gridcells',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
