# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layouts', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tiempo_espera', models.IntegerField()),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_lugar', models.ForeignKey(db_column='id_lugar', on_delete=django.db.models.deletion.DO_NOTHING, to='lugares.lugares')),
                ('id_version', models.ForeignKey(db_column='id_version', on_delete=django.db.models.deletion.DO_NOTHING, to='layouts.layouts')),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['id_evento'],
            },
        ),
    ]
