# Generated by Django 6.0.3 on 2026-03-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
