# Generated by Django 6.0.3 on 2026-03-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventos_descripcion_eventos_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='estatus',
        ),
    ]
