# Generated by Django 6.0.3 on 2026-03-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_eventos_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='estatus',
            field=models.BooleanField(default=1),
        ),
    ]
