# Generated by Django 6.0.3 on 2026-04-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
