# Generated by Django 6.0.3 on 2026-04-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], max_length=10),
        ),
    ]
