# Generated by Django 6.0.3 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_eventos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='foto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
