# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientos', '0001_initial'),
        ('eventos', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id_ticket', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('id_asiento', models.ForeignKey(db_column='id_asiento', on_delete=django.db.models.deletion.DO_NOTHING, to='asientos.asientos')),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.eventos')),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='ordenes.ordenes')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['id_ticket'],
            },
        ),
    ]
