# Generated by Django 6.0.3 on 2026-04-11 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos', '0002_asientos_id_grid_cell_estadoasientoevento'),
        ('grid_cells', '0002_alter_gridcells_id_zona'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='id_grid_cell',
            field=models.ForeignKey(blank=True, db_column='id_grid_cell', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grid_cells.gridcells'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id_asiento',
            field=models.ForeignKey(blank=True, db_column='id_asiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='asientos.asientos'),
        ),
    ]
