# Generated by Django 6.0.1 on 2026-04-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
