# Generated by Django 6.0.3 on 2026-04-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=60),
            preserve_default=False,
        ),
    ]
