# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layouts',
            fields=[
                ('id_layout', models.BigAutoField(primary_key=True, serialize=False)),
                ('grid_rows', models.IntegerField()),
                ('grid_cols', models.IntegerField()),
                ('version', models.IntegerField()),
                ('estatus', models.CharField(max_length=9)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_dueno', models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
                ('id_lugar', models.ForeignKey(db_column='id_lugar', on_delete=django.db.models.deletion.DO_NOTHING, to='lugares.lugares')),
            ],
            options={
                'db_table': 'layouts',
                'ordering': ['id_layout'],
            },
        ),
    ]
