# Generated by Django 6.0.3 on 2026-04-05 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
        ('lugares', '0001_initial'),
        ('usuarios', '0002_usuarios_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='layouts',
            name='checksum_layout',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='layouts',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layouts',
            name='layout_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], max_length=9),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='id_dueno',
            field=models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.PROTECT, related_name='layouts_creados', to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='layouts',
            name='id_lugar',
            field=models.ForeignKey(db_column='id_lugar', on_delete=django.db.models.deletion.PROTECT, related_name='layouts', to='lugares.lugares'),
        ),
    ]
