# Generated by Django 6.0.1 on 2026-04-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_layouts_checksum_layout_layouts_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layouts',
            name='checksum_layout',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
