# Generated by Django 6.0.1 on 2026-04-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_alter_layouts_checksum_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layouts',
            name='checksum_layout',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
