# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id_lugar', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=150)),
                ('estatus', models.CharField(max_length=12)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_dueno', models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'lugares',
                'ordering': ['id_lugar'],
            },
        ),
    ]
