# Generated by Django 6.0.1 on 2026-04-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
