# Generated by Django 6.0.3 on 2026-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zona', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=7)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
                ('id_layout', models.ForeignKey(db_column='id_layout', on_delete=django.db.models.deletion.DO_NOTHING, to='layouts.layouts')),
            ],
            options={
                'db_table': 'zonas',
                'ordering': ['id_zona'],
            },
        ),
    ]
